---
title: "JSC370 Final Project"
author: "Yinuo Zhao"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Final Project website.


```{r message=FALSE, echo=FALSE, include=FALSE, warning=FALSE}

library(tidyverse)
library(plotly)
library(widgetframe)
library(tidytext)

```

```{r, echo=FALSE}
### load Starbucks and state-level data ###
sb_locs <- read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2024/main/labs/lab11/starbucks-locations.csv", show_col_types = FALSE)

sb_nutr <- read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2024/main/labs/lab11/starbucks-menu-nutrition.csv", show_col_types = FALSE)

usa_pop <- read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2024/main/labs/lab11/us_state_pop.csv", show_col_types = FALSE)

usa_states<-read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2024/main/labs/lab11/states.csv", show_col_types = FALSE)


### Merge data ###
sb_usa <- sb_locs |> filter(Country=="US")

sb_locs_state <- sb_usa |>
  group_by(`State/Province`) |>
  rename(state=`State/Province`) |>
  summarize(n_stores=n())

# need state abbreviations
usa_pop_abbr <- 
  full_join(usa_pop, usa_states, 
            by = join_by(state == State)
  ) 

sb_locs_state <- full_join(sb_locs_state, usa_pop_abbr,
                           by = join_by (state == Abbreviation))


### Get topwords from menu items ###

topwords <- sb_nutr |>
  unnest_tokens(word, Item, token="words") |>
  group_by(word) |>
  summarise(word_frequency = n()) |>
  arrange(across(word_frequency, desc)) |>
  head(10)

```



# Part 1

## Showcasing plots {.tabset}

### Figure 1

```{r plot_2, echo=FALSE, source="process_starbucks_data.R"}
p1 <- ggplot(data = sb_locs_state, aes(x=population, y=n_stores, color = state)) + 
  geom_point(alpha = 0.8) +
  labs(title = "Number of Starbucks and Population of States", x="Population", y = "Number of Starbucks")

ggplotly(p1)
```

### Figure 2

```{r plot_1, echo=FALSE, source="process_starbucks_data.R"}
p2 <- ggplot(data = sb_nutr, aes(x=Calories, fill = Category)) + 
  geom_histogram(alpha=0.3, bins = 30, position = "identity")+ 
  labs(title = "Caloric Distribution of Starbucks menu items by Category(drinks and food)", y = "Count")

ggplotly(p2)
